### ISSUE TITLE
use `{{ path('something') }}` for MediaConch

### ISSUE THREAD

**Issue by retokromer** [MediaArea/MediaArea-Website#125]
At https://github.com/MediaArea/MediaArea-Website/blob/master/src/RAWcookedBundle/Resources/views/Default/index.html.twig#L51 should there not be something like
```
<a href="{{ path('mc_home') }}">MediaConch</a>
```
as well?

**Comment by JeromeMartinez** [comment]
MediaConch is not yet in Synfony version of the website (historical reasons, this is the last one we need to move to Synfony version of MediaArea), reason it has not his Synfony path yet.

**Comment by retokromer** [comment]
OK, then closing.
