### ISSUE TITLE
mismatch between #nttw2 and #nttw3

### ISSUE THREAD

**Issue by retokromer** [MediaArea/MediaArea-Website#194]
On page https://mediaarea.net/Vote/No-Time-To-Wait-3-Conference-5 there is a mismatch between edition 2 and 3:

<img width="1063" alt="bildschirmfoto 2018-06-09 um 21 01 50" src="https://user-images.githubusercontent.com/3246607/41195144-8322e9ce-6c28-11e8-9c4c-395bb94ceca8.png">

As I don’t know where this is, therefore I cannot open a PR to fix it. As there is now information…

**Comment by JeromeMartinez** [comment]
Votes are in a dedicated DB, not in the repo.
The reference was when there was no NTTW3 page, I changed the text.

**Comment by retokromer** [comment]
FYI @JeromeMartinez The link is still to 2.
