### ISSUE TITLE
NTTW5 link

### ISSUE THREAD

**Issue by retokromer** [MediaArea/MediaArea-Website#320]
<img width="565" alt="Screenshot 2020-01-28 at 13 01 07" src="https://user-images.githubusercontent.com/3246607/73262391-55fe0280-41ce-11ea-9e2f-26bab3e7f1ce.png">

Sorry, I don’t have the time to open a PR now.

**Comment by JeromeMartinez** [comment]
Oops, I missed that during my review. Thanks for the report, fix is online now.
