### ISSUE TITLE
DV analyser images are missing

### ISSUE THREAD

**Issue by kieranjol** [MediaArea/MediaArea-Website#81]
https://mediaarea.net/DVAnalyzer/dv-video-error-concealment

Not sure if it's the case in other pages as well. I was going to link to this page in a AMIA-L listserv post but I might link to the AVPreserve page in the interim..

**Comment by JeromeMartinez** [comment]
We fix that soon, please wait a bit.

**Comment by kieranjol** [comment]
aaaaand the avpreserve page is dead too https://www.avpreserve.com/dvanalyzer/video-error-concealment/

I'll wait!

**Comment by JeromeMartinez** [comment]
Due to Flash player nowadays deactivated by browsers. But nowadays browsers support native video playback, we switch.

**Comment by kieranjol** [comment]
Hey, I'm going to send on the mail to the listserv as it needs to go through a moderation process anyhow.

**Comment by JeromeMartinez** [comment]
you can link to the MediaArea page, we are fixing the page in the meanwhile.

**Comment by kieranjol** [comment]
Will do! sending now.

**Comment by GuillaumeRoques** [comment]
Fixed in #82 and available now on the website

**Comment by kieranjol** [comment]
Yay, thanks!! The email should eventually appear in this thread once it gets past the moderators =

Thanks @GuillaumeRoques  and @JeromeMartinez !
